- hosts: centos 
  remote_user: root
  tasks:
    - name: epel-release
      yum: name=epel-release state=latest

    - name: vim 
      yum: name=vim state=latest

    - name: rsync
      yum: name=rsync state=latest

    - name: 时间同步 ntp
      yum: name=ntp state=latest

    - name: 开机启动 ntp
      shell: systemctl enable ntpd

    - name: 重启 ntpd 
      shell: systemctl restart ntpd


