---

- hosts: all
  remote_user: root
  tasks:
    - name: 启用洪水攻击抵御
      shell: echo 1 > /proc/sys/net/ipv4/tcp_syncookies
     
    - name: 开启重用。允许将TIME-WAIT sockets重新用于新的TCP连接
      shell: echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
     
    - name: 启用timewait快速回收
      shell: echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
     
    - name: 对于本端断开的socket连接时间
      shell: echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
    
    - name: 让sysctl.conf生效
      shell: sysctl -p   
         
