
- hosts: hadoop 
  remote_user: root
  tasks:
    - name: java
      yum: name=java-1.8.0-openjdk,java-1.8.0-openjdk-devel state=latest 

#    - name: source
#      copy: src=./hadoop-3.0.3 dest=/opt/
#
    - name: link 
      file: src=/opt/hadoop-2.7.6 dest=/opt/hadoop state=link 

    - name: conf
      copy: src=./opt/hadoop/etc/hadoop/ dest=/opt/hadoop/etc/hadoop/

    - name: .bashrc
      copy: src=./.bashrc dest=~/.bashrc

    - name: source 
      shell: source ~/.bashrc
