
- hosts: cluster
  remote_user: root
  tasks:
#    - name: java
#      yum: name=java-1.8.0-openjdk,java-1.8.0-openjdk-devel state=latest 
#
#    - name: source
#      copy: src=./hadoop-3.0.3 dest=/opt/
#
#    - name: link 
#      file: src=/opt/hadoop-3.0.3 dest=/opt/hadoop state=link 
#
    - name: .bashrc
      copy: src=./.bashrc dest=~/.bashrc

- hosts: cluster-master
  remote_user: root
  tasks:
    - name: conf
      copy: src=./opt/hadoop/etc/hadoop/core-site.xml dest=/opt/hadoop/etc/hadoop/

    - name: conf
      copy: src=./opt/hadoop/etc/hadoop/hdfs-site.xml dest=/opt/hadoop/etc/hadoop/

    - name: conf
      copy: src=./opt/hadoop/etc/hadoop/mapred-site.xml dest=/opt/hadoop/etc/hadoop/

    - name: conf
      copy: src=./opt/hadoop/etc/hadoop/yarn-site.xml dest=/opt/hadoop/etc/hadoop/


- hosts: cluster-slave
  remote_user: root
  tasks:
    - name: conf
      copy: src=./opt/hadoop/etc/hadoop dest=/opt/hadoop/etc/
